version: '3'

services:
    nginx:
        container_name: nginx_container
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - app-network

    php:
        container_name: php_container
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "9001:9000"
        depends_on:
            - mysql
            - redis
        networks:
            - app-network

    mysql:
        container_name: mysql_container
        image: mysql:5.7
        platform: linux/amd64
        restart: always
        environment:
            MYSQL_DATABASE: zmenu
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

    redis:
        container_name: redis_container
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
        external: true

volumes:
    mysql_data:
